In [1]:
import pandas as pd

vol = pd.read_csv('./data/original/vol.csv')
vol2 = pd.read_csv('./data/original/vol2.csv')
visual = pd.read_csv('./data/original/visual.csv')
visual2 = pd.read_csv('./data/original/visual2.csv')

In [2]:
vol = vol.drop(vol.columns[-9:], axis=1)
visual = visual.drop(visual.columns[-2:], axis=1)

In [3]:
# sort rows a-z by certain column
vol = vol.sort_values(by='ID')
vol2 = vol2.sort_values(by='ID')
visual = visual.sort_values(by='ID')
visual2 = visual2.sort_values(by='ID')

# reset index
vol = vol.reset_index(drop=True)
vol2 = vol2.reset_index(drop=True)
visual = visual.reset_index(drop=True)
visual2 = visual2.reset_index(drop=True)

In [4]:
print(visual.shape)
print(visual2.shape)

(394, 7)
(78, 9)

In [5]:
# replace all NaN with 0 and "x" with 1
visual2 = visual2.replace({'x': 1, float('nan'): 0})

In [6]:
visual.head()

         ID  PCA  thalamus  cerebellum  pons  midbrain side
0  003aa3e8    0         1           0     0         0    L
1  0214eb85    0         0           1     0         0    R
2  035bf9fe    0         0           1     0         0    L
3  037cfba0    0         0           0     1         0    L
4  0559cdbf    0         1           0     0         1    L

In [7]:
visual2.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumL,cerebellumR,pons,midbrain
0,sub-00223b5a,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,sub-003d54e0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,sub-00f0ea23,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,sub-01b2897a,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,sub-0522f021,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [8]:
# add to visual the following columns: PCAL	PCAR	ThalamusL	ThalamusR	cerebellumL	cerebellumR
visual['PCAL'] = 0
visual['PCAR'] = 0
visual['thalamusL'] = 0
visual['thalamusR'] = 0
visual['cerebellumL'] = 0
visual['cerebellumR'] = 0

In [9]:
#if PCA is 1, and side is L, then PCAL is 1
# if PCA is 1, and side is R, then PCA R is 1
# if Thalamus is 1, and side is L, then ThalamusL is 1
# if Thalamus is 1, and side is R, then ThalamusR is 1
# if cerebellum is 1, and side is L, then cerebellumL is 1
# if cerebellum is 1, and side is R, then cerebellumR is 1

visual.loc[(visual['PCA'] == 1) & (visual['side'] == 'L'), 'PCAL'] = 1
visual.loc[(visual['PCA'] == 1) & (visual['side'] == 'R'), 'PCAR'] = 1
visual.loc[(visual['thalamus'] == 1) & (visual['side'] == 'L'), 'thalamusL'] = 1
visual.loc[(visual['thalamus'] == 1) & (visual['side'] == 'R'), 'thalamusR'] = 1
visual.loc[(visual['cerebellum'] == 1) & (visual['side'] == 'L'), 'cerebellumL'] = 1
visual.loc[(visual['cerebellum'] == 1) & (visual['side'] == 'R'), 'cerebellumR'] = 1

visual.head()

,ID,PCA,thalamus,cerebellum,pons,midbrain,side,PCAL,PCAR,thalamusL,thalamusR,cerebellumL,cerebellumR
0,003aa3e8,0,1,0,0,0,L,0,0,1,0,0,0
1,0214eb85,0,0,1,0,0,R,0,0,0,0,0,1
2,035bf9fe,0,0,1,0,0,L,0,0,0,0,1,0
3,037cfba0,0,0,0,1,0,L,0,0,0,0,0,0
4,0559cdbf,0,1,0,0,1,L,0,0,1,0,0,0

In [10]:
visual = visual.drop(columns=['side'])
visual = visual.drop(columns=['cerebellum'])
visual = visual.drop(columns=['thalamus'])
visual = visual.drop(columns=['PCA'])

In [11]:
visual.head()

,ID,pons,midbrain,PCAL,PCAR,thalamusL,thalamusR,cerebellumL,cerebellumR
0,003aa3e8,0,0,0,0,1,0,0,0
1,0214eb85,0,0,0,0,0,0,0,1
2,035bf9fe,0,0,0,0,0,0,1,0
3,037cfba0,1,0,0,0,0,0,0,0
4,0559cdbf,0,1,0,0,1,0,0,0

In [12]:
# move pons and midbrain columns to back
cols = list(visual.columns.values)
cols.pop(cols.index('pons'))
cols.pop(cols.index('midbrain'))
visual = visual[cols+['pons', 'midbrain']]

In [13]:
# rename thalamusL as ThalamusL
visual = visual.rename(columns={'thalamusL': 'ThalamusL'})
visual = visual.rename(columns={'thalamusR': 'ThalamusR'})
visual.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumL,cerebellumR,pons,midbrain
0,003aa3e8,0,0,1,0,0,0,0,0
1,0214eb85,0,0,0,0,0,1,0,0
2,035bf9fe,0,0,0,0,1,0,0,0
3,037cfba0,0,0,0,0,0,0,1,0
4,0559cdbf,0,0,1,0,0,0,0,1

In [14]:
vol.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumR,cerebellumL,pons,midbrain
0,003aa3e8,0,0,401,0,0,0,0,0
1,0214eb85,0,0,0,0,0,3950,529,0
2,035bf9fe,0,0,0,0,3314,0,0,0
3,037cfba0,0,0,0,0,0,0,2277,0
4,0559cdbf,0,0,469,0,0,0,0,625

In [15]:
visual2.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumL,cerebellumR,pons,midbrain
0,sub-00223b5a,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,sub-003d54e0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,sub-00f0ea23,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,sub-01b2897a,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,sub-0522f021,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [16]:
vol2.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumR,cerebellumL,pons,midbrain
0,sub-00223b5a,0,0,0,486,0,3958,970,0
1,sub-003d54e0,0,0,0,0,0,0,1847,278
2,sub-00f0ea23,3869,40235,0,0,0,81,0,0
3,sub-01b2897a,0,0,543,0,0,0,0,0
4,sub-0522f021,3932,55438,0,1683,0,1468,0,149

In [17]:
# if PCAL is 0 and PCAR is 0, then PCA is 0
# if PCAL is 1 and PCAR is 0, then PCA is 1
# if PCAR is 0, and PCAL is 1, then PCA is 2
# if both PCAL and PCAR are 1, then PCA is 3

visual2.loc[(visual2['PCAL'] == 0) & (visual2['PCAR'] == 0), 'PCA'] = 0
visual2.loc[(visual2['PCAL'] == 1) & (visual2['PCAR'] == 0), 'PCA'] = 1
visual2.loc[(visual2['PCAL'] == 0) & (visual2['PCAR'] == 1), 'PCA'] = 2
visual2.loc[(visual2['PCAL'] == 1) & (visual2['PCAR'] == 1), 'PCA'] = 3

visual2.loc[(visual2['ThalamusL'] == 0) & (visual2['ThalamusR'] == 0), 'Thalamus'] = 0
visual2.loc[(visual2['ThalamusL'] == 1) & (visual2['ThalamusR'] == 0), 'Thalamus'] = 1
visual2.loc[(visual2['ThalamusL'] == 0) & (visual2['ThalamusR'] == 1), 'Thalamus'] = 2
visual2.loc[(visual2['ThalamusL'] == 1) & (visual2['ThalamusR'] == 1), 'Thalamus'] = 3

visual2.loc[(visual2['cerebellumL'] == 0) & (visual2['cerebellumR'] == 0), 'cerebellum'] = 0
visual2.loc[(visual2['cerebellumL'] == 1) & (visual2['cerebellumR'] == 0), 'cerebellum'] = 1
visual2.loc[(visual2['cerebellumL'] == 0) & (visual2['cerebellumR'] == 1), 'cerebellum'] = 2
visual2.loc[(visual2['cerebellumL'] == 1) & (visual2['cerebellumR'] == 1), 'cerebellum'] = 3

visual.loc[(visual['PCAL'] == 0) & (visual['PCAR'] == 0), 'PCA'] = 0
visual.loc[(visual['PCAL'] == 1) & (visual['PCAR'] == 0), 'PCA'] = 1
visual.loc[(visual['PCAL'] == 0) & (visual['PCAR'] == 1), 'PCA'] = 2
visual.loc[(visual['PCAL'] == 1) & (visual['PCAR'] == 1), 'PCA'] = 3

visual.loc[(visual['ThalamusL'] == 0) & (visual['ThalamusR'] == 0), 'Thalamus'] = 0
visual.loc[(visual['ThalamusL'] == 1) & (visual['ThalamusR'] == 0), 'Thalamus'] = 1
visual.loc[(visual['ThalamusL'] == 0) & (visual['ThalamusR'] == 1), 'Thalamus'] = 2
visual.loc[(visual['ThalamusL'] == 1) & (visual['ThalamusR'] == 1), 'Thalamus'] = 3

visual.loc[(visual['cerebellumL'] == 0) & (visual['cerebellumR'] == 0), 'cerebellum'] = 0
visual.loc[(visual['cerebellumL'] == 1) & (visual['cerebellumR'] == 0), 'cerebellum'] = 1
visual.loc[(visual['cerebellumL'] == 0) & (visual['cerebellumR'] == 1), 'cerebellum'] = 2
visual.loc[(visual['cerebellumL'] == 1) & (visual['cerebellumR'] == 1), 'cerebellum'] = 3

In [18]:
visual2.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumL,cerebellumR,pons,midbrain,PCA,Thalamus,cerebellum
0,sub-00223b5a,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
1,sub-003d54e0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,sub-00f0ea23,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
3,sub-01b2897a,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,sub-0522f021,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0

In [19]:
vol2.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumR,cerebellumL,pons,midbrain
0,sub-00223b5a,0,0,0,486,0,3958,970,0
1,sub-003d54e0,0,0,0,0,0,0,1847,278
2,sub-00f0ea23,3869,40235,0,0,0,81,0,0
3,sub-01b2897a,0,0,543,0,0,0,0,0
4,sub-0522f021,3932,55438,0,1683,0,1468,0,149

In [20]:
visual.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumL,cerebellumR,pons,midbrain,PCA,Thalamus,cerebellum
0,003aa3e8,0,0,1,0,0,0,0,0,0.0,1.0,0.0
1,0214eb85,0,0,0,0,0,1,0,0,0.0,0.0,2.0
2,035bf9fe,0,0,0,0,1,0,0,0,0.0,0.0,1.0
3,037cfba0,0,0,0,0,0,0,1,0,0.0,0.0,0.0
4,0559cdbf,0,0,1,0,0,0,0,1,0.0,1.0,0.0

In [21]:
vol.head()

,ID,PCAL,PCAR,ThalamusL,ThalamusR,cerebellumR,cerebellumL,pons,midbrain
0,003aa3e8,0,0,401,0,0,0,0,0
1,0214eb85,0,0,0,0,0,3950,529,0
2,035bf9fe,0,0,0,0,3314,0,0,0
3,037cfba0,0,0,0,0,0,0,2277,0
4,0559cdbf,0,0,469,0,0,0,0,625

In [22]:
# merge vol and visual
vol_visual = pd.merge(vol, visual, on='ID')
vol_visual['Dataset'] = "old"

vol_visual2 = pd.merge(vol2, visual2, on='ID')
vol_visual2['Dataset'] = "new"

complete_vol_visual = pd.concat([vol_visual, vol_visual2])
complete_vol_visual.to_csv('./complete_vol_visual.csv', index=False)

In [23]:
PCA1 = pd.concat([vol['ID'], vol['PCAL'], vol['PCAR'], visual['PCA']], axis=1)
PCA2 = pd.concat([vol2['ID'], vol2['PCAL'], vol2['PCAR'], visual2['PCA']], axis=1)

PCA = PCA[PCA.PCA != 0]

NameError: name 'PCA' is not defined

In [ ]:
PCA.to_csv('./PCA.csv', index=False)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

X = pd.concat([PCA['PCAL'], PCA['PCAR']], axis=1)
y = PCA['PCA']

# Set up cross-validation:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

# Perform cross-validation:
cv_scores = cross_val_score(model, X, y, cv=kf)

# Print cross-validated scores:
print("Cross-validated scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate the model:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy of the model on the test set:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Cross-validated scores: [1. 1. 1. 1. 1.]
Average cross-validation score: 1.0
Accuracy of the model on the test set: 1.0
Confusion Matrix:
 [[4 0 0]
 [0 1 0]
 [0 0 3]]

In [ ]:
from sklearn.metrics import accuracy_score

def classify_brain_parts(df, threshold_low, threshold_high):
    epsilon = 1e-5  # Small number to prevent division by zero
    # Calculate the ratio of left to right brain parts
    df['ratio'] = df['PCAL'] / (df['PCAR'] + epsilon)
    
    # Classification based on ratio
    df['predicted'] = df['ratio'].apply(lambda x: 3 if threshold_low <= x <= threshold_high else (1 if x > threshold_high else 2))
    return df

def find_best_thresholds(df):
    best_accuracy = 0
    best_thresholds = (0, 0)
    
    # Test various thresholds
    for low in [i * 0.01 for i in range(50, 150)]:  # Testing thresholds from 0.5 to 1.4
        for high in [i * 0.01 for i in range(100, 200)]:  # Testing thresholds from 1.0 to 1.9
            if high > low:
                classified_df = classify_brain_parts(df.copy(), low, high)
                accuracy = accuracy_score(classified_df['PCA'], classified_df['predicted'])
                if accuracy > best_accuracy:
                    best_accuracy = accuracy
                    best_thresholds = (low, high)
    
    return best_thresholds, best_accuracy

# Find the best thresholds
best_thresholds, best_accuracy = find_best_thresholds(PCA)
print(f"Best thresholds: Low={best_thresholds[0]}, High={best_thresholds[1]} with accuracy: {best_accuracy}")

Best thresholds: Low=0.5, High=1.29 with accuracy: 0.7894736842105263

In [ ]:
Thalamus = pd.concat([vol2['ID'], vol2['ThalamusL'], vol2['ThalamusR'], visual2['Thalamus']], axis=1)

Thalamus = Thalamus[Thalamus.Thalamus != 0]

In [ ]:
Thalamus.to_csv('./Thalamus.csv', index=False)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

X = pd.concat([Thalamus['ThalamusL'], Thalamus['ThalamusR']], axis=1)
y = Thalamus['Thalamus']

# Set up cross-validation:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

# Perform cross-validation:
cv_scores = cross_val_score(model, X, y, cv=kf)

# Print cross-validated scores:
print("Cross-validated scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())

# You can also train the model and test on a holdout set if needed:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate the model:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy of the model on the test set:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Cross-validated scores: [1.   0.75 1.   1.   0.75]
Average cross-validation score: 0.9
Accuracy of the model on the test set: 1.0
Confusion Matrix:
 [[3 0]
 [0 2]]

In [ ]:
cerebellum = pd.concat([vol2['ID'], vol2['cerebellumL'], vol2['cerebellumR'], visual2['cerebellum']], axis=1)

cerebellum = cerebellum[cerebellum.cerebellum != 0]

In [ ]:
cerebellum.head()

              ID  cerebellumL  cerebellumR  cerebellum
0   sub-00223b5a         3958            0         2.0
5   sub-05c53a88        15668            0         2.0
7   sub-10f21b45            0         3229         1.0
11  sub-1c72de90          578            0         3.0
12  sub-1e9e8d3a        31895          461         2.0

In [ ]:
cerebellum.to_csv('./cerebellum.csv', index=False)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

X = pd.concat([cerebellum['cerebellumL'], cerebellum['cerebellumR']], axis=1)
y = cerebellum['cerebellum']

# Set up cross-validation:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)

# Perform cross-validation:
cv_scores = cross_val_score(model, X, y, cv=kf)

# Print cross-validated scores:
print("Cross-validated scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())

# You can also train the model and test on a holdout set if needed:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate the model:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy of the model on the test set:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Cross-validated scores: [0.71428571 1.         0.66666667 0.83333333 1.        ]
Average cross-validation score: 0.8428571428571429
Accuracy of the model on the test set: 0.7142857142857143
Confusion Matrix:
 [[1 0 1]
 [0 2 1]
 [0 0 2]]

In [ ]:
# cerebellum has a lot of artificats --> aka a lot of noise which reduces accuracy
# TODO: give cases that were misclassified
# going to go through this manually
# TODO: simple threshold for each brain region
# doesn't work as well
# TODO: also try ratio
# doesnt work as well
# TODO: similar table, with volumes as well. add side
# done
# TODO: for old, make table with vol and side so dr. faria can determine if bilateral
# inter evaluator agreement

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Splitting data into features and target
X = pd.concat([PCA['PCAL'], PCA['PCAR']], axis=1)
y = PCA['PCA']

# Splitting data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Decision Tree Classifier
dt_classifier = OneVsRestClassifier(DecisionTreeClassifier())
dt_classifier.fit(X_train, y_train)
dt_predictions = dt_classifier.predict(X_test)

# Random Forest Classifier
rf_classifier = OneVsRestClassifier(RandomForestClassifier())
rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

# Support Vector Machine Classifier
svm_classifier = OneVsRestClassifier(SVC())
svm_classifier.fit(X_train, y_train)
svm_predictions = svm_classifier.predict(X_test)

# Evaluating the models
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_predictions))
print("Random Forest Accuracy:", accuracy_score(y_test, rf_predictions))
print("SVM Accuracy:", accuracy_score(y_test, svm_predictions))

# Detailed classification report for one of the models
print("\nClassification Report for Random Forest:")
print(classification_report(y_test, rf_predictions))

Decision Tree Accuracy: 0.75
Random Forest Accuracy: 0.75
SVM Accuracy: 0.625

Classification Report for Random Forest:
              precision    recall  f1-score   support

         1.0       0.67      1.00      0.80         4
         2.0       1.00      1.00      1.00         1
         3.0       1.00      0.33      0.50         3

    accuracy                           0.75         8
   macro avg       0.89      0.78      0.77         8
weighted avg       0.83      0.75      0.71         8

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import itertools

# Prepare the data
X = pd.concat([PCA['PCAL'], PCA['PCAR']], axis=1).values
y = PCA['PCA'].values

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Splitting data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert to torch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long) - 1  # Convert labels to zero-indexed
y_test = torch.tensor(y_test, dtype=torch.long) - 1

# Hyperparameters grid
learning_rates = [0.001, 0.01]
batch_sizes = [32, 64]
num_epochs_options = [30, 50]

# Define the neural network
class StrokeNet(nn.Module):
    def __init__(self, input_size, hidden1, hidden2, num_classes):
        super(StrokeNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden1)
        self.fc2 = nn.Linear(hidden1, hidden2)
        self.fc3 = nn.Linear(hidden2, num_classes)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Grid search over hyperparameters
best_accuracy = 0
best_params = {}

for lr, batch_size, num_epochs in itertools.product(learning_rates, batch_sizes, num_epochs_options):
    # Create dataloaders
    train_dataset = TensorDataset(X_train, y_train)
    test_dataset = TensorDataset(X_test, y_test)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    # Initialize the network
    model = StrokeNet(input_size=2, hidden1=128, hidden2=64, num_classes=3)

    # Loss and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    # Training the model
    for epoch in range(num_epochs):
        for inputs, labels in train_loader:
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    # Evaluate the model
    model.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for inputs, labels in test_loader:
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
        
        accuracy = 100 * correct / total
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_params = {'lr': lr, 'batch_size': batch_size, 'num_epochs': num_epochs}

print(f'Best Accuracy: {best_accuracy:.2f}%')
print(f'Best Parameters: {best_params}')

Best Accuracy: 75.00%
Best Parameters: {'lr': 0.001, 'batch_size': 32, 'num_epochs': 50}